### ISSUE TITLE
Create volume for specific folder

### ISSUE THREAD

**Issue by maxnowack** [woohhan/dropbox-csi#28]
Is it possible to create a persistent volume for a specific folder of my dropbox?

**Comment by woohhan** [comment]
@maxnowack Hi, Thanks for the question. Currently, It is not possible to mount a path other than the root directory. However, I'm considering implementing this feature, and I would like to add it to the feature if possible. Thanks.

**Comment by woohhan** [comment]
This feature was added in commit 23bac07e74f32028ac62024810a4e527e0c64006. You can see how to use it in the following example: https://github.com/woohhan/dropbox-csi/blob/master/deploy/pod.yaml#L18. Thanks for the suggestion.

**Comment by maxnowack** [comment]
Nice, thank you!
